tf_ids: data/all_tf_ids.txt
protein_fasta: /projectnb/bradham/data/ReferenceSequences/wray-genome/L_var_proteins.fasta
transcript_fasta: /projectnb/bradham/data/ReferenceSequences/wray-genome/L_var_transcripts.fasta
annos: /projectnb/bradham/data/ReferenceSequences/wray-genome/annotations/master_top_hits.txt
hmm: /projectnb/bradham/PFAM/Pfam-A.hmm
eval: 0.001
input:
  id_to_name: data/all_tf_models.csv
  motif_dir: "data/informative_motifs"
allowed_domains:
  domain_regex: ["^zf-", "T-box", "^bZIP", "^Homeobox", "^GATA", "DNA-bind", "HMG-box", "Winged helix"]
  files: ["data/HMG-box_clans.txt", "data/HTH_clans.txt", "data/Leucine-zipper_clans.txt", "data/OB-fold_clans.txt", "data/Zinc-finger_clans.txt", 'data/misc_domains.txt']
blast_db: "swissprot.fasta"
output:
  dir: "output"
  ensembl_dir: "output/ensembl_output"
workflows:
  domain_detection:
    snakefile: /projectnb/bradham/workflows/domain_identification/Snakefile
    ensembl_config: files/ensembl_domain_detect.yaml